name: Security Workflow
on: [push]

jobs:
  Secrets-Scanning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Gitleaks - Installation
        run: |
          wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz
          tar -xvf gitleaks.tar.gz
          chmod +x gitleaks 
          mv gitleaks /usr/local/bin
          gitleaks detect . -v --redact -f json -r secrets-scanning-report.json
      - name: Upload Secrets Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: secrets-scanning-report
          path: secrets-scanning-report.json
